### ISSUE TITLE
Recommendations for further usage

### ISSUE THREAD

**Issue by JulianGerhard21** [cpcdoy/rust-sbert#21]
Hi,

first of all: thanks for that amazing port. I finally managed to get it working even under windows.

Are there any recommendations for further usage of the computed vectors in regards to similarity measurements? 

My plan now would have been to embed a given search query as well and then calculate the cosine similarity between search query and dataset entry for each entry from the processed "dataset".

Is there anything against this approach? Are there any more advanced libraries that you know of?

Thanks in advance for the support. I would be open for contribution in any case.

Kind regards
Julian

**Comment by cpcdoy** [comment]
Hi @JulianGerhard21,

Sorry for the very late reply, this somehow slipped through all my notifications!

The approach you are mentioning is actually the exact usage of the [sentence-transformers](https://github.com/UKPLab/sentence-transformers) library from which this repo is heavily inspired. [Here's how you could do it](https://www.sbert.net/docs/quickstart.html#comparing-sentence-similarities), and it's exactly what you described.

The models are trained in such a way that the vector space spanned by these models, when you embed sentences, will make it so that cosine similarity between the sentence embedding vectors will make sense in determining how close the sentences are.

Take a look at the [papers Nils Reimers's team has published](https://www.sbert.net/docs/publications.html#) for more details.

Hope this helps!
