### ISSUE TITLE
a few questions: hf vs rust tokenizers, and cuda support?

### ISSUE THREAD

**Issue by getorca** [cpcdoy/rust-sbert#23]
Sorry, very green to rust. 

how does performance of the huggingface vs rust tokenizers compare? 

Is cuda supported?

**Comment by cpcdoy** [comment]
I haven't done any recent benchmark of those two tokenizer libraries, they are continuously getting updated so I'd suggest trying on your end each and seeing which one is fastest for your use case, because sometimes performance can be use case dependent. You can also go check directly on their repository pages (both linked in this repo's [README](https://github.com/cpcdoy/rust-sbert#rust-sbert---) at the top).

CUDA is supported yes.
